apiVersion: synthetics.kentiklabs.com/v1
kind: SyntheticTask
metadata:
  name: demo
spec:
  kentik_site: "CHANGEME"
  fetch:
    - service: demo
      target: /
      port: 8080
      method: GET
      period: 60s
      expiry: 5s
  ping:
    - name: demo
      kind: service
      protocol: tcp
      port: 8080
      count: 1
      period: 60s
      expiry: 5s
      timeout: 1000
